// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb77jAzMUQ9daJS-031NxU7KCmuLKXJhQ',
    appId: '1:626197422204:web:5c6a6954a067277e9069f9',
    messagingSenderId: '626197422204',
    projectId: 'todo-ed5ce',
    authDomain: 'todo-ed5ce.firebaseapp.com',
    storageBucket: 'todo-ed5ce.appspot.com',
    measurementId: 'G-7DWZ5NPEB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbkcny8cK53I3rXfXo2lwKvS3-lZVkoU',
    appId: '1:626197422204:android:41ed5beda64acfd19069f9',
    messagingSenderId: '626197422204',
    projectId: 'todo-ed5ce',
    storageBucket: 'todo-ed5ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE36pylJPOUAKUXLXGODewTEqfjVo72SI',
    appId: '1:626197422204:ios:dedd17a978b38e729069f9',
    messagingSenderId: '626197422204',
    projectId: 'todo-ed5ce',
    storageBucket: 'todo-ed5ce.appspot.com',
    iosBundleId: 'com.example.todoAppFirebase',
  );
}
